/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package rentacar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class AddCar extends javax.swing.JInternalFrame {
    private PreparedStatement  SaveCar; 
    private Connection connection = null;
    private ResultSet rs;
    private  DataBaseConnection dbc; 
    private String query ;
    String NumberPlate;
            
    /**
     * Creates new form AddCar
     */
    public AddCar() {
        initComponents();
        dbc = new DataBaseConnection();
        connection = dbc.dbcon();
        
        setSize(1000, 600);
        setLocation(50 , 50);
          setTitle("Add New Car");
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("OWNER NAME*");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 160, 100, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("BRAND");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 200, 70, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("MODEL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 200, 100, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("COLOR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 250, 70, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("RENT PRICE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 250, 80, 25);

        jButton1.setText("EDIT CAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 310, 240, 50);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 120, 240, 25);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 160, 240, 25);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(660, 160, 240, 25);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 200, 240, 25);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(180, 250, 240, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 28)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADD NEW CAR");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 10, 1000, 70);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("NUMBER PLATE*");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 120, 110, 25);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(660, 200, 240, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("OWNER CONTACT #");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 160, 120, 25);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(660, 250, 240, 25);

        jButton2.setText("ADD CAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 310, 240, 50);

        jButton3.setText("UPDATE CAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(660, 310, 240, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

           
        try {
            
        String query =   "insert into cars (numberplate, ownerName, brand, model, color,  ownercontact,rentprice ) values(?,?,?,?,?,?,?)";
             
                    
            SaveCar = connection.prepareStatement(query);
             
            SaveCar.setString(1,jTextField1.getText().trim());
            SaveCar.setString(2,jTextField2.getText().trim());
            SaveCar.setString(3,jTextField4.getText().trim());
            SaveCar.setString(4,jTextField6.getText().trim());
            SaveCar.setString(5,jTextField5.getText().trim());
            SaveCar.setString(6,jTextField3.getText().trim());
            SaveCar.setDouble( 7,Double.parseDouble(jTextField7.getText().trim())); 
                         
            SaveCar.execute();
             
                    
           JOptionPane.showMessageDialog(null, "Car Added Successfully....");
              
           jTextField1.setText("");
           jTextField2.setText("");
           jTextField3.setText("");
           jTextField4.setText("");
           jTextField5.setText("");
           jTextField6.setText("");
           jTextField7.setText("");
           jTextField1.requestFocus();
           
           
           
           
        }catch(Exception ec){
        
        
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String NumberPlate = JOptionPane.showInputDialog("Enter Number Plate");
try {
            
        String query =   "select * from cars where numberplate = '"+NumberPlate+"'";
               
        SaveCar = connection.prepareStatement(query);
             
            
            rs = SaveCar.executeQuery();
            rs.next();
            
            jTextField1.setText( rs.getString(1));
            jTextField2.setText( rs.getString(2));
            jTextField4.setText( rs.getString(3));
            jTextField6.setText( rs.getString(4));
            jTextField5.setText( rs.getString(5));
            jTextField3.setText( rs.getString(6));
            jTextField7.setText( rs.getString(7));
           
            
              
            jTextField1.setEditable(false);
           
            jButton2.setEnabled(false);
           
           
           
           
        }catch(Exception ec){
        
        
        }



            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

 try {
         
               
        SaveCar = null;
        String UpdateString = "update cars set ownerName = ? , brand=? , model = ?, color=?, ownercontact=?, rentprice=? "
                + " where numberplate = ? ";
        
        SaveCar = connection.prepareStatement(UpdateString);
         
        SaveCar.setString(1 , jTextField2.getText());
        SaveCar.setString(2 , jTextField4.getText());
        SaveCar.setString(3 , jTextField6.getText()); 
        SaveCar.setString(4 , jTextField5.getText()); 
        SaveCar.setString(5 , jTextField3.getText()); 
        SaveCar.setDouble(6 , Double.parseDouble(jTextField7.getText())); 
          
        SaveCar.setString(7 , jTextField1.getText());
        SaveCar.executeUpdate();
        JOptionPane.showMessageDialog(null, "Car Updated Successfully....." );
        
        
        
            jTextField1.setText( "");
            jTextField2.setText( "");
            jTextField4.setText( "");
            jTextField6.setText( "");
            jTextField5.setText( "");
            jTextField3.setText( "");
            jTextField7.setText( "");
           
            
              
            jTextField1.setEditable(true);
        
        jButton2.setEnabled(true);
        
        
        }catch(Exception ere){
        System.out.println(ere.getMessage());
        }
        
        
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
