
package rentacar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class BookingRecord extends javax.swing.JInternalFrame {

    
     private  DefaultTableModel dmodel = new DefaultTableModel(new Object[][]
     {
         { null, null, null , null, null },
     },new String [] 
     {
        "Book Code", "Driver Name", "Car", "Customer Name", "Customer Cell", "From " ,   "To" , "Booking Date" ,"Total Rent"
    }); 
      
    private PreparedStatement  BStatement; 
    private Connection connection = null;
    private ResultSet rs;
    private  DataBaseConnection dbc;   
    private  SimpleDateFormat df =new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date  FDate, TDate;
    private java.sql.Date sqlfDate, sqlTDate;
    
    /**
     * Creates new form BookingRecord
     */
    public BookingRecord() {
        initComponents();
        
         dbc = new DataBaseConnection();
        connection = dbc.dbcon();
        
       
         setSize(1200, 600);
         setLocation(50 , 50);
         setTitle("Search A Car");
          dmodel.setNumRows(0);
         setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SEARCH A CAR");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 10, 1100, 70);

        jTable1.setModel(dmodel);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 1140, 370);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("FROM DATE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 90, 90, 25);

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(120, 90, 310, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("TO DATE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 90, 70, 25);

        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(510, 90, 310, 25);

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(830, 90, 330, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

                    try{
                        
                         int row = 0;
                    dmodel.setNumRows(0);
                    FDate = jDateChooser1.getDate();
                    TDate = jDateChooser2.getDate();    
                    sqlfDate = new java.sql.Date(FDate.getTime());
                    sqlTDate = new java.sql.Date(TDate.getTime());
                    String Query = "select * from booking where bookdate between ? and ? ";
                    BStatement = connection.prepareStatement(Query);
                    BStatement.setDate(1  , sqlfDate);
                    BStatement.setDate(2  , sqlTDate);
                    
                     rs = BStatement.executeQuery();
                    
                     while(rs.next())
                    {
                    dmodel.addRow(new Object[]{"" , "" ,"","",""});  
                    jTable1.setValueAt( rs.getString(1)  , row, 0);
                    jTable1.setValueAt( rs.getString(2)  , row, 1);
                    jTable1.setValueAt( rs.getString(3)  , row, 2);
                    jTable1.setValueAt( rs.getString(4)  , row, 3);
                     jTable1.setValueAt( rs.getString(5)  , row, 4);
                     jTable1.setValueAt( rs.getString(6)  , row, 5);
                     jTable1.setValueAt( rs.getString(7)  , row, 6);
                     jTable1.setValueAt( rs.getString(8)  , row, 5);
                     jTable1.setValueAt( rs.getString(9)  , row, 6);
                     
             row++;
            }
                     
                    
                    }catch(Exception sd){}
                    
                    
                    
                    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
