/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package rentacar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class CarRecord extends javax.swing.JInternalFrame {

    
    
    private PreparedStatement  SaveCar; 
    private Connection connection = null;
    private ResultSet rs;
    private  DataBaseConnection dbc; 
    
     private  DefaultTableModel dmodel = new DefaultTableModel(new Object[][]
     {
         { null, null, null , null, null },
     },new String [] 
     {
        "Number Plate", "Owner Name", "Brand", "Model", "Color", "Onwner Contact" ,   "Rent Price"
    }); 
     
    String QueryString ;
    
    /**
     * Creates new form CarRecord
     */
    public CarRecord() {
        initComponents();
        
        dbc = new DataBaseConnection();
        connection = dbc.dbcon();
        dmodel.setNumRows(0);
        setSize(1000, 600);
        setLocation(50 , 50);
        
        
        
         try{
           int row = 0;
           dmodel.setNumRows(0);    
           QueryString = "Select * from cars";
           
            SaveCar = connection.prepareStatement( QueryString);
            rs = SaveCar.executeQuery();
            while(rs.next())
            {
             dmodel.addRow(new Object[]{"" , "" ,"","",""});  
             jTable1.setValueAt( rs.getString(1)  , row, 0);
             jTable1.setValueAt( rs.getString(2)  , row, 1);
             jTable1.setValueAt( rs.getString(3)  , row, 2);
             jTable1.setValueAt( rs.getString(4)  , row, 3);
             jTable1.setValueAt( rs.getString(5)  , row, 4);
             jTable1.setValueAt( rs.getString(6)  , row, 5);
             jTable1.setValueAt( rs.getString(7)  , row, 6);
             row++;
            }
            
           }catch(Exception  dfd){ System.out.println(dfd.getMessage() );}
        
        
        
        
        
        setVisible(true);
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CAR RECORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 10, 960, 70);

        jTable1.setModel(dmodel);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 920, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
