/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentacar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * 
 */
public class LoginForm extends javax.swing.JFrame {

    private PreparedStatement  SusStatement; 
    private Connection connection = null;
    private ResultSet rs;
    private  DataBaseConnection dbc; 
    private String query ;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        dbc = new DataBaseConnection();
        connection = dbc.dbcon();
        setSize(550, 300);
      
         setLocationRelativeTo(null);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 0));
        setForeground(new java.awt.Color(204, 255, 204));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("USER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 110, 100, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 110, 210, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 153, 100, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(180, 150, 210, 22);

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 200, 100, 25);

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 200, 110, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentacar/images/rent.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 10, 160, 80);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 230, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         System.out.println("cliecked");
        try{
       
       query = "select * from user  where username=? and password=?";
       SusStatement =  connection.prepareStatement(query);
       SusStatement.setString(1, jTextField1.getText());
        SusStatement.setString(2, jPasswordField1.getText()); 
       rs = SusStatement.executeQuery();
     
      
       if(rs.next()) {
      
       this.setVisible(false);
       connection.close();
       SusStatement.close();
       rs.close();
      new MainFrame();
       }
       else 
       {
       
       jLabel3.setText("Wromg User Name or Password");
       }    
         
       
       }catch(SQLException esl){System.out.println(esl.getMessage());}
        
                
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
            System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
