/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package rentacar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class SearchCar extends javax.swing.JInternalFrame {

    
     private  DefaultTableModel dmodel = new DefaultTableModel(new Object[][]
     {
         { null, null, null , null, null },
     },new String [] 
     {
        "Number Plate", "Owner Name", "Brand", "Model", "Color", "Onwner Contact" ,   "Rent Price"
    }); 
      
    private PreparedStatement  SaveCar; 
    private Connection connection = null;
    private ResultSet rs;
    private  DataBaseConnection dbc;   
    
    
    /**
     * Creates new form SearchCar
     */
    public SearchCar() {
        initComponents();
        
         dbc = new DataBaseConnection();
        connection = dbc.dbcon();
        
       
         setSize(1000, 600);
         setLocation(50 , 50);
         setTitle("Search A Car");
          dmodel.setNumRows(0);
         setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SEARCH A CAR");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 10, 1000, 70);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("SEARCH BY MODEL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 100, 120, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 150, 180, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Model", "Number Plate", "Color" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 100, 180, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DETAILS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 150, 120, 20);

        jButton1.setText("SEARCH CAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 190, 180, 30);

        jTable1.setModel(dmodel);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 240, 910, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          
        
           try{
           int row = 0;
           dmodel.setNumRows(0);    
           String SearchString =""; 
           String SearchText = "";
           String QueryString ="";
           SearchString = jComboBox1.getSelectedItem().toString();
           SearchText = jTextField1.getText();
          
           if(SearchString.equals("Owner"))
           {
           SearchString = "ownerName";
          
           }else if (SearchString.equals("Model"))
           {
            SearchString = "model";
           }else if (SearchString.equals("Number Plate"))
           {
           SearchString = "numberplate";
           
           }    
           else 
           {
             SearchString = "color";
           
           }    
           
           
           QueryString = "Select * from cars where "+SearchString+" =  '"+SearchText+"'";
           
           System.out.println(QueryString);
           
            SaveCar = connection.prepareStatement( QueryString);
            rs = SaveCar.executeQuery();
            while(rs.next())
            {
             dmodel.addRow(new Object[]{"" , "" ,"","",""});  
             jTable1.setValueAt( rs.getString(1)  , row, 0);
             jTable1.setValueAt( rs.getString(2)  , row, 1);
             jTable1.setValueAt( rs.getString(3)  , row, 2);
             jTable1.setValueAt( rs.getString(4)  , row, 3);
             jTable1.setValueAt( rs.getString(5)  , row, 4);
             jTable1.setValueAt( rs.getString(6)  , row, 5);
             jTable1.setValueAt( rs.getString(7)  , row, 6);
             row++;
            }
            
           }catch(Exception  dfd){ System.out.println(dfd.getMessage() );
           }
                                                                  
          
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
